/**
 * Pushtaini Masala Collection — 12 Royal Rajasthani Spice Blends
 * Each masala is named in Pushtaini royal style with a family character.
 * Based on the most famous dishes from royal Rajasthani restaurants and heritage kitchens.
 */

export interface Masala {
  id: string;
  name: string;
  royalName: string;
  hindiName: string;
  tagline: string;
  character: string;
  characterTitle: string;
  description: string;
  story: string;
  culturalNote: string;
  dish: string;
  dishDescription: string;
  color: string;
  accentColor: string;
  spiceType: "turmeric" | "chili" | "cumin" | "coriander" | "saffron" | "cardamom" | "cinnamon" | "mixed";
  ingredients: string[];
  aromaNote: string;
}

export const masalas: Masala[] = [
  {
    id: "laal-maas-masala",
    name: "Laal Maas Masala",
    royalName: "Dada Ji's Laal Maas",
    hindiName: "दादा जी का लाल मांस",
    tagline: "Fire of the Rajputs",
    character: "Dada Ji",
    characterTitle: "The Spice Guardian — Since 1897",
    description: "A fiery crimson blend born from the warrior kitchens of Rajputana. Mathania chilies and 14 rare spices create the legendary heat that defined royal Rajput feasts.",
    story: "Dada Ji spent 60 years perfecting this blend at the foot of Mehrangarh Fort. His hands, stained red from decades of grinding Mathania chilies, knew the exact moment when the spices released their soul. This is his legacy — untamed, unapologetic, unforgettable.",
    culturalNote: "Laal Maas was the warrior's reward — served after victorious battles in the courts of Udaipur and Jaipur. Its fiery red color symbolized valor and courage in Rajput culture.",
    dish: "Laal Maas",
    dishDescription: "Fiery red mutton curry cooked in mustard oil with whole Mathania chilies",
    color: "#C44536",
    accentColor: "#8B1A1A",
    spiceType: "chili",
    ingredients: ["Mathania Chili", "Garlic", "Coriander Seeds", "Cumin", "Cloves", "Cardamom", "Cinnamon", "Fennel"],
    aromaNote: "Intense smoky heat with deep garlic warmth and a complex spice undertow",
  },
  {
    id: "dal-baati-masala",
    name: "Dal Baati Churma Masala",
    royalName: "Rani Sa's Dal Baati",
    hindiName: "रानी सा का दाल बाटी",
    tagline: "The Soul of Marwar",
    character: "Rani Sa",
    characterTitle: "Queen of the Royal Kitchen",
    description: "A robust blend of 18 hand-ground spices that transforms simple lentils into the legendary Dal Baati Churma — the crown jewel of Rajasthani cuisine.",
    story: "Rani Sa believed that the finest masala must be ground at dawn, when the desert air is cool and the spices hold their oils. Her Dal Baati Masala was served at every royal feast in the zenana — a recipe so precious, it was written in gold ink on silk.",
    culturalNote: "Dal Baati is not merely food in Rajasthan — it is an emotion, a celebration, a homecoming. Every wedding, every festival, every reunion begins and ends with this sacred dish.",
    dish: "Dal Baati Churma",
    dishDescription: "Crispy wheat baatis dipped in ghee, served with five-lentil dal and sweet churma",
    color: "#E5A100",
    accentColor: "#D4963A",
    spiceType: "turmeric",
    ingredients: ["Cumin", "Coriander", "Turmeric", "Asafoetida", "Red Chili", "Bay Leaf", "Cloves", "Black Pepper"],
    aromaNote: "Earthy warmth with smoky undertones and a whisper of asafoetida",
  },
  {
    id: "gatte-ka-masala",
    name: "Gatte Ka Masala",
    royalName: "Maharaja Sa's Gatte",
    hindiName: "महाराजा सा का गट्टे",
    tagline: "Desert Ingenuity",
    character: "Maharaja Sa",
    characterTitle: "The Royal Connoisseur",
    description: "A tangy, aromatic blend crafted for the iconic besan gatte — proof that Rajasthani genius can create extraordinary flavors from the simplest ingredients.",
    story: "Maharaja Sa would accept no ordinary Gatte ki Sabzi at his table. He commissioned the royal spice master to create a blend so perfect that even gram flour dumplings would taste like a feast fit for coronation. This is that blend — unchanged for 127 years.",
    culturalNote: "Gatte ki Sabzi represents the resourcefulness of Marwari women who turned pantry staples into dishes that rivaled royal cuisine. It's served at every Rajasthani thali as a mark of culinary pride.",
    dish: "Gatte ki Sabzi",
    dishDescription: "Spiced gram flour dumplings simmered in tangy yogurt gravy",
    color: "#D4963A",
    accentColor: "#A0926B",
    spiceType: "saffron",
    ingredients: ["Cumin", "Coriander", "Turmeric", "Red Chili", "Fenugreek", "Mustard Seeds", "Asafoetida", "Dried Mango"],
    aromaNote: "Tangy yogurt warmth with mustard seed crackle and fenugreek bitterness",
  },
  {
    id: "ker-sangri-masala",
    name: "Ker Sangri Masala",
    royalName: "Dadi Sa's Ker Sangri",
    hindiName: "दादी सा का केर सांगरी",
    tagline: "Treasures of the Thar",
    character: "Dadi Sa",
    characterTitle: "Keeper of Desert Secrets",
    description: "A unique desert spice blend designed for the wild-harvested ker berries and sangri beans — the jewels of Thar Desert cuisine that grow nowhere else on earth.",
    story: "Dadi Sa walked the desert at dawn, gathering ker berries and sangri pods from the sacred Khejri trees. She knew every plant by name, every season by scent. Her masala blend honors 500 years of Bishnoi wisdom — the art of turning desert treasures into gold.",
    culturalNote: "Ker Sangri is Rajasthan's most unique dish — made entirely from desert-foraged ingredients. The Bishnoi community, protectors of the Khejri tree, have preserved this tradition for over 500 years.",
    dish: "Ker Sangri",
    dishDescription: "Wild desert berries and beans cooked with mustard oil and desert spices",
    color: "#6B8E23",
    accentColor: "#4A7C59",
    spiceType: "coriander",
    ingredients: ["Mustard Seeds", "Fennel", "Red Chili", "Turmeric", "Amchur", "Cumin", "Nigella Seeds", "Fenugreek"],
    aromaNote: "Wild and earthy with sharp mustard oil pungency and desert herb notes",
  },
  {
    id: "safed-maas-masala",
    name: "Safed Maas Masala",
    royalName: "Kunwar Sa's Safed Maas",
    hindiName: "कुंवर सा का सफेद मांस",
    tagline: "The White Royal",
    character: "Kunwar Sa",
    characterTitle: "The Young Prince — Heir to the Throne",
    description: "An ethereal white spice blend of cashews, almonds, and cream-colored aromatics — crafted for the legendary white curry served only at Rajput royal weddings.",
    story: "When young Kunwar Sa tasted Safed Maas for the first time at his father's coronation feast, he declared it 'the color of moonlight, the taste of heaven.' He spent years learning the exact ratio of white spices that creates this ivory masterpiece.",
    culturalNote: "In Rajput tradition, Safed Maas is served on silver thalis during wedding feasts. Its white color symbolizes new beginnings, and it remains the most prestigious dish in Rajasthani non-vegetarian cuisine.",
    dish: "Safed Maas",
    dishDescription: "Creamy white mutton curry with cashew paste, cream, and white spices",
    color: "#FFF8E7",
    accentColor: "#F5DEB3",
    spiceType: "cardamom",
    ingredients: ["White Pepper", "Green Cardamom", "Mace", "Cashews", "Almonds", "Poppy Seeds", "Cream", "Melon Seeds"],
    aromaNote: "Delicate cream and cashew with ethereal cardamom and white pepper warmth",
  },
  {
    id: "mohan-maas-masala",
    name: "Mohan Maas Masala",
    royalName: "Thakur Sa's Mohan Maas",
    hindiName: "ठाकुर सा का मोहन मांस",
    tagline: "The Enchanter's Feast",
    character: "Thakur Sa",
    characterTitle: "The Noble Lord — Master of Feasts",
    description: "An opulent, milk-based spice blend with saffron and dry fruits — crafted for the most luxurious curry in Rajasthani cuisine, once served only to Maharajas.",
    story: "Thakur Sa hosted the grandest feasts in all of Mewar. His Mohan Maas was legendary — cooked in reduced milk with saffron worth its weight in gold. Visiting dignitaries would offer kingdoms for this recipe. He took it to his grave. Until now.",
    culturalNote: "Mohan Maas — 'the enchanting meat' — was reserved for the most important diplomatic feasts. When a Maharaja wished to honor a visiting dignitary above all others, Mohan Maas was the ultimate compliment.",
    dish: "Mohan Maas",
    dishDescription: "Rich mutton curry cooked in reduced milk with saffron, almonds, and cardamom",
    color: "#DAA520",
    accentColor: "#B8860B",
    spiceType: "saffron",
    ingredients: ["Saffron", "Cardamom", "Mace", "Almonds", "Cashews", "Cream", "Raisins", "White Pepper"],
    aromaNote: "Luxurious saffron-milk richness with almond cream and royal cardamom",
  },
  {
    id: "jungli-maas-masala",
    name: "Jungli Maas Masala",
    royalName: "Rawat Sa's Jungli Maas",
    hindiName: "रावत सा का जंगली मांस",
    tagline: "Wild Hunt Legacy",
    character: "Rawat Sa",
    characterTitle: "The Warrior Hunter — Untamed Spirit",
    description: "A primal, minimalist spice blend — just salt, red chilies, and fierce heat — recreating the wild game curry that Rajput hunters cooked over campfires in the Aravalli forests.",
    story: "Rawat Sa rode into the Aravallis before dawn, returning only when his hunt was complete. He cooked over open flame with nothing but ghee, meat, and this fierce masala. No pretense. No complexity. Just the raw, untamed flavor of a warrior's reward.",
    culturalNote: "Jungli Maas represents the untamed spirit of Rajput warrior culture — no pretense, no complexity, just pure primal flavor. It's still cooked outdoors during hunting festivals and camping trips across Rajasthan.",
    dish: "Jungli Maas",
    dishDescription: "Wild-style meat curry with minimal spices, maximum heat, cooked over open flame",
    color: "#FF4500",
    accentColor: "#DC143C",
    spiceType: "chili",
    ingredients: ["Whole Red Chilies", "Garlic", "Salt", "Ghee", "Black Pepper", "Bay Leaf", "Raw Onion", "Mustard Oil"],
    aromaNote: "Primal smoke and fire with aggressive chili heat and raw garlic punch",
  },
  {
    id: "mirchi-vada-masala",
    name: "Mirchi Vada Masala",
    royalName: "Chhote Sarkar's Mirchi Vada",
    hindiName: "छोटे सरकार का मिर्ची वड़ा",
    tagline: "Jodhpur's Street Crown",
    character: "Chhote Sarkar",
    characterTitle: "The Youngest — Street Food Rebel",
    description: "A bold, punchy blend that captures the spirit of Jodhpur's legendary street food — where fat green chilies are stuffed with spiced potato and deep-fried to golden perfection.",
    story: "Chhote Sarkar broke tradition. While the elders guarded royal recipes, he ventured into Jodhpur's lanes and fell in love with street food. He brought the Mirchi Vada recipe home, elevated it with Pushtaini spices, and created a bridge between royal heritage and street soul.",
    culturalNote: "Mirchi Vada is Jodhpur's identity food — as iconic as the Blue City itself. Every visitor's first stop is a Mirchi Vada stall, and every Jodhpuri living abroad craves this taste of home above all else.",
    dish: "Mirchi Vada",
    dishDescription: "Large green chilies stuffed with spiced potato, battered and deep-fried",
    color: "#4A7C59",
    accentColor: "#2E8B57",
    spiceType: "cardamom",
    ingredients: ["Cumin", "Fennel", "Amchur", "Red Chili", "Coriander", "Black Salt", "Garam Masala", "Chaat Masala"],
    aromaNote: "Sharp green chili freshness with tangy amchur and warm fennel sweetness",
  },
  {
    id: "rajasthani-chai-masala",
    name: "Rajasthani Chai Masala",
    royalName: "Bua Sa's Chai Masala",
    hindiName: "बुआ सा की चाय मसाला",
    tagline: "Desert Dawn Elixir",
    character: "Bua Sa",
    characterTitle: "The Family Elder — Keeper of Warmth",
    description: "A warming chai blend born from the cold desert nights of Jaisalmer — where camel herders brew thick, spiced tea over open fires beneath star-filled skies.",
    story: "Bua Sa's chai was legendary. Guests would travel from three villages just for one cup. Her secret? Extra ginger for the soul, saffron for the heart, and a prayer whispered into every batch. No machine could replicate what her hands created at dawn.",
    culturalNote: "Rajasthani chai culture is unique — the tea is boiled for long minutes until thick and creamy, served in small kullads that add an earthy flavor. Offering chai to guests is the first law of Rajasthani hospitality.",
    dish: "Rajasthani Masala Chai",
    dishDescription: "Thick, creamy spiced tea brewed with milk, jaggery, and desert spices",
    color: "#8B4513",
    accentColor: "#D2691E",
    spiceType: "cinnamon",
    ingredients: ["Ginger", "Cardamom", "Cinnamon", "Black Pepper", "Cloves", "Saffron", "Nutmeg", "Star Anise"],
    aromaNote: "Warming ginger-cardamom embrace with saffron luxury and pepper bite",
  },
  {
    id: "ghevar-masala",
    name: "Ghevar Masala",
    royalName: "Rani Sa's Ghevar Masala",
    hindiName: "रानी सा का घेवर मसाला",
    tagline: "Sweet Royal Alchemy",
    character: "Rani Sa",
    characterTitle: "Queen of the Royal Kitchen",
    description: "A delicate aromatic blend of cardamom, saffron, and rose — the secret behind Rajasthan's most celebrated festival sweet, the honeycomb-like Ghevar.",
    story: "Every Teej, Rani Sa would personally prepare the Ghevar masala — crushing Kashmiri saffron between her gold-ringed fingers, mixing Pushkar roses with Mysore cardamom. The aroma would fill the entire zenana, announcing that the festival had truly begun.",
    culturalNote: "Ghevar is not just a sweet — it's a symbol of monsoon celebrations in Rajasthan. Newly married brides receive elaborate Ghevar platters from their maternal homes during Teej.",
    dish: "Ghevar",
    dishDescription: "Honeycomb-shaped disc sweet soaked in sugar syrup, topped with rabri and nuts",
    color: "#FFD700",
    accentColor: "#E5A100",
    spiceType: "saffron",
    ingredients: ["Saffron", "Green Cardamom", "Rose Petals", "Nutmeg", "Mace", "Kewra", "Pistachios", "Almonds"],
    aromaNote: "Intoxicating saffron-rose bouquet with warm cardamom and delicate kewra",
  },
  {
    id: "papad-ki-sabzi-masala",
    name: "Papad Ki Sabzi Masala",
    royalName: "Dadi Sa's Papad Sabzi",
    hindiName: "दादी सा का पापड़ सब्जी",
    tagline: "Marwari Minimalism",
    character: "Dadi Sa",
    characterTitle: "Keeper of Desert Secrets",
    description: "A quick-fire spice blend that transforms humble papads into an extraordinary curry — the ultimate expression of Marwari culinary philosophy: maximum flavor from minimum ingredients.",
    story: "Dadi Sa could feed a family of twelve from an empty pantry. Her Papad ki Sabzi was proof — five minutes, three ingredients, and this masala. Guests never knew they were eating a 'poverty dish.' They thought it was a royal delicacy. That was Dadi Sa's magic.",
    culturalNote: "This dish embodies the Marwari business philosophy — efficiency without compromise. Like their legendary business acumen, this recipe achieves extraordinary results with minimal resources.",
    dish: "Papad ki Sabzi",
    dishDescription: "Crispy papad pieces in a spiced yogurt and tomato gravy",
    color: "#CD853F",
    accentColor: "#8B4513",
    spiceType: "cumin",
    ingredients: ["Cumin", "Coriander", "Turmeric", "Red Chili", "Asafoetida", "Mustard Seeds", "Curry Leaves", "Ginger"],
    aromaNote: "Quick-fire cumin crackle with sharp asafoetida and warm ginger",
  },
  {
    id: "chakki-masala",
    name: "Chakki Masala",
    royalName: "Dada Ji's Chakki Special",
    hindiName: "दादा जी का चक्की स्पेशल",
    tagline: "Stone-Ground Heritage",
    character: "Dada Ji",
    characterTitle: "The Spice Guardian — Since 1897",
    description: "A rustic, full-bodied blend ground on traditional stone chakki mills — preserving the volatile oils and complex flavors that modern grinding destroys.",
    story: "Dada Ji refused to let machines touch his spices. 'The chakki knows,' he would say, 'it remembers every masala it has ever ground.' His 200-year-old stone mill in Pushkar still turns at dawn, producing this blend exactly as it was made when the British still ruled.",
    culturalNote: "The chakki (stone mill) is sacred in Rajasthani homes. Brides bring their mother's chakki as part of their dowry, carrying forward generations of spice-grinding wisdom.",
    dish: "Bajre ki Roti with Lehsun Chutney",
    dishDescription: "Pearl millet flatbread served with garlic chutney and white butter",
    color: "#A0522D",
    accentColor: "#6B4226",
    spiceType: "cinnamon",
    ingredients: ["Coriander", "Cumin", "Black Pepper", "Cloves", "Cinnamon", "Bay Leaf", "Nutmeg", "Dried Ginger"],
    aromaNote: "Deeply rustic with stone-ground earthiness and warm cinnamon bark",
  },
];

export const packagingOptions = [
  {
    id: "royal-box",
    name: "Dada Ji's Heritage Box",
    description: "Dark navy box with gold filigree borders and Dada Ji's portrait — the Spice Guardian grinding masala in his brass mortar. Airtight seal preserves freshness for 18 months.",
    size: "100g",
    type: "Premium Collection",
    character: "Dada Ji",
  },
  {
    id: "rani-box",
    name: "Rani Sa's Royal Edition",
    description: "Elegant box featuring Rani Sa holding a brass bowl of spices, framed in ornate Rajasthani jali patterns. A gift worthy of queens.",
    size: "100g",
    type: "Premium Collection",
    character: "Rani Sa",
  },
  {
    id: "brass-tin",
    name: "Dadi Sa's Brass Tin",
    description: "Hand-finished brass tin with Dadi Sa's portrait engraved on the lid — the Keeper of Desert Secrets offering her treasured spice thali. Opens to reveal vibrant masala inside.",
    size: "75g",
    type: "Travel Friendly",
    character: "Dadi Sa",
  },
  {
    id: "gift-chest",
    name: "Maharaja Sa's Spice Chest",
    description: "Velvet-lined wooden chest featuring all 5 royal characters. Contains 6 signature masalas in gold-capped glass jars. The ultimate Pushtaini gift.",
    size: "6 × 75g",
    type: "Gift Collection",
    character: "Maharaja Sa",
  },
  {
    id: "travel-set",
    name: "Chhote Sarkar's Travel Kit",
    description: "Compact brass tins in a leather travel pouch — for the young rebel who carries heritage wherever they go. TSA-friendly, airtight, and impossibly stylish.",
    size: "30g × 4",
    type: "Travel Friendly",
    character: "Chhote Sarkar",
  },
];
